name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Push generated package to GitHub registry and NuGet
        run: |
          cd gua64
          dotnet build
          dotnet pack
          dotnet nuget push .\bin\Release\*.nupkg -s github -SkipDuplicate
          dotnet nuget push .\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -SkipDuplicate -k ${{ secrets.NUGET_API_KEY }}